[package]
name = "nix-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "13.0.0"
lalrpop-util = "0.20.0"
bytecode = "0.3.0"
rnix = "0.11.0"

macros = { path = "./src/macros" }

[build-dependencies]
lalrpop = "0.20.2"
